session:
  expiration: 7d
  expired_clear_interval: 1m

docker:
  host: unix:///var/run/docker.sock
  image_label: amplitude-runner # TODO: remove
  name_prefix: amplitude-runner/
  languages:
    - python
